def hailstone(n: int) -> int:
    """
    Calculate the length of the Hailstone sequence starting at n.
    The sequence is generated by:
    - If n is even, next number is n/2
    - If n is odd, next number is 3*n + 1
    The sequence ends when n becomes 1.
    """
    length = 1
    while n > 1:
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
        length += 1
    return length

if __name__ == "__main__":
    while True:
        number = input("Please enter a positive integer (enter 'q' to quit): ")
        if number.lower() == 'q':
            print("Program ended")
            break
        try:
            n = int(number)
            if n <= 0:
                print("Please enter a positive integer!")
                continue
            result = hailstone(n)
            print(f"Hailstone sequence length: {result}")
        except ValueError:
            print("Invalid input, please enter a number!")